import * as React from 'react';
import { connect } from 'react-redux';
import Timeline from './Timeline'

const Info = () => (
    <div>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Sit amet consectetur adipiscing elit pellentesque habitant morbi tristique senectus. Auctor neque vitae tempus quam pellentesque. Egestas purus viverra accumsan in nisl nisi scelerisque eu ultrices. Diam phasellus vestibulum lorem sed risus. Tristique magna sit amet purus gravida quis blandit turpis cursus. In fermentum posuere urna nec. Mollis aliquam ut porttitor leo a diam sollicitudin tempor. Sollicitudin nibh sit amet commodo nulla facilisi nullam vehicula. Nibh ipsum consequat nisl vel pretium lectus quam id leo. Hendrerit dolor magna eget est lorem ipsum dolor. Quam elementum pulvinar etiam non quam lacus suspendisse faucibus. Ipsum faucibus vitae aliquet nec ullamcorper sit amet risus. Elementum sagittis vitae et leo. Luctus accumsan tortor posuere ac. Convallis aenean et tortor at risus. Ultrices gravida dictum fusce ut placerat orci. Habitant morbi tristique senectus et. Id donec ultrices tincidunt arcu non sodales.</p>
        <p>Urna duis convallis convallis tellus id interdum. Eget velit aliquet sagittis id consectetur. Ut sem viverra aliquet eget sit amet tellus. Tempor commodo ullamcorper a lacus vestibulum. Fringilla ut morbi tincidunt augue interdum velit euismod in pellentesque. Convallis posuere morbi leo urna molestie at. Nec dui nunc mattis enim ut tellus. A lacus vestibulum sed arcu non. Amet commodo nulla facilisi nullam vehicula ipsum. Cras adipiscing enim eu turpis egestas pretium aenean pharetra. Cras semper auctor neque vitae tempus quam pellentesque. Feugiat in ante metus dictum at tempor commodo ullamcorper. Egestas fringilla phasellus faucibus scelerisque eleifend donec. Auctor urna nunc id cursus metus. Mus mauris vitae ultricies leo integer malesuada nunc. Vestibulum sed arcu non odio. Eget egestas purus viverra accumsan in nisl nisi scelerisque. Vulputate odio ut enim blandit volutpat maecenas volutpat. Fermentum dui faucibus in ornare quam viverra orci sagittis.</p>
        <p>Metus dictum at tempor commodo ullamcorper a. Blandit turpis cursus in hac habitasse platea. Mi quis hendrerit dolor magna. Malesuada pellentesque elit eget gravida. Aliquet nibh praesent tristique magna. Egestas egestas fringilla phasellus faucibus scelerisque eleifend donec pretium. Duis ultricies lacus sed turpis tincidunt id. Ullamcorper morbi tincidunt ornare massa eget egestas purus viverra. Purus faucibus ornare suspendisse sed. Sed cras ornare arcu dui vivamus. Eleifend mi in nulla posuere sollicitudin aliquam ultrices. Feugiat sed lectus vestibulum mattis ullamcorper velit sed. Proin sagittis nisl rhoncus mattis. Imperdiet dui accumsan sit amet nulla. Interdum velit laoreet id donec ultrices tincidunt. Dignissim convallis aenean et tortor at risus viverra. Malesuada fames ac turpis egestas integer eget aliquet nibh.</p>
        <Timeline />
    </div>
);

export default connect()(Info);
